# Generated by Django 4.2.5 on 2023-09-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excursions', models.CharField()),
                ('location', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Cruise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('duration', models.IntegerField()),
                ('sale_from', models.CharField()),
                ('destinations', models.ManyToManyField(to='main_app.destination')),
            ],
        ),
    ]
