# Generated by Django 4.2.5 on 2023-09-15 22:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=50)),
                ('email', models.TextField()),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='cruise',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='sale_from',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='destination',
            name='excursions',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='destination',
            name='location',
            field=models.CharField(max_length=250),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('I', 'Interior'), ('O', 'Ocean View'), ('B', 'Balcony'), ('JS', 'Junior Suite'), ('S', 'Suite')], default='I', max_length=50)),
                ('number', models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(500), django.core.validators.MinValueValidator(100)])),
                ('location', models.CharField(choices=[('P', 'Portside'), ('S', 'Starboard Side'), ('F', 'Front of Ship'), ('BS', 'Back of Ship')], default='P', max_length=50)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.booking')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='cruise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.cruise'),
        ),
        migrations.AddField(
            model_name='booking',
            name='destinations',
            field=models.ManyToManyField(to='main_app.destination'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.user'),
        ),
    ]
