# Generated by Django 4.2.5 on 2023-09-18 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_booking_user_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cruise',
            old_name='sale_from',
            new_name='sail_from',
        ),
    ]
