# Generated by Django 4.2.5 on 2023-09-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_sale_from_cruise_sail_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=500)),
                ('description', models.TextField(default='', max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='destination',
            name='description',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.RemoveField(
            model_name='destination',
            name='excursions',
        ),
        migrations.AddField(
            model_name='destination',
            name='excursions',
            field=models.ManyToManyField(to='main_app.excursion'),
        ),
    ]
