# Generated by Django 4.2.5 on 2023-09-19 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_excursion_destination_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='number',
            new_name='cabin_number',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='destinations',
        ),
    ]
