# Generated by Django 4.2.5 on 2023-09-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rename_number_room_cabin_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cruise',
            name='picturepath',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='destination',
            name='picturepath',
            field=models.CharField(default='', max_length=500),
        ),
    ]
