# Generated by Django 4.2.5 on 2023-09-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_destination_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='picturepath',
            field=models.CharField(default='', max_length=500),
        ),
    ]
