# Generated by Django 4.2.5 on 2023-09-20 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_room_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='price',
        ),
    ]
